### PR TITLE
Fix desktop-environment-toggle-mute fails if remote buffers active

### PR DESCRIPTION
**Pull request by divansantana**

### CODE REVIEW

**Comment by divansantana** [comment]
@DamienCassou I know very little about emacs-lisp.  Though this PR works to fix #16 and took me a little while :grin:  .

Is that optimal?

Other functions in the project problably have similar issues.  Should I update the PR for them?

**Comment by DamienCassou** [comment]
Thank you very much for your work.

> Is that optimal?

I don't know but I'm fine merging something like that.

> Other functions in the project problably have similar issues. Should I update the PR for them?

the same PR could fix all of them. But please make sure that your code is only written once and not for each command. Something like:

```emacs
(defun desktop-environment-toggle-mute ()
  "Toggle between muted and un-muted."
  (interactive)
  (message "%s"
           (desktop-environment--shell-command-to-string desktop-environment-volume-toggle-command)))

(defun desktop-environment--shell-command-to-string (...)
  "..."
   (let ((default-directory temporary-file-directory))
      (shell-command-to-string ...)))
```

**Comment by divansantana** [comment]
@DamienCassou thanks for the tips and help.  It should be in order now.

Thanks.

**Review by DamienCassou — CHANGES_REQUESTED** [review]
Excellent work, thank you! Final step is to squash all your commits into 1 and make sure it is up-to-date with master.

**Comment by divansantana** [comment]
Done. I updated my branch, after squashing the commits into one.  Therefore there is a merge commit in my PR, hope that's in order.

**Comment by DamienCassou** [comment]
> Done. I updated my branch, after squashing the commits into one. Therefore there is a merge commit in my PR, hope that's in order.

the merge commit is not necessary, please remove it by rebasing on top of latest master:

```session
$ git rebase origin/master
```

**Comment by divansantana** [comment]
Fixed.

**Review by DamienCassou — APPROVED** [review]
Awesome, thank you!

**Pull request merged**
